name: Publish release changelog
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: pmm_release
        run: |
          git clone --depth 1 https://github.com/percona/pmm-doc doc
          cd doc/docs/release-notes
          version="${release_tag/refs\/tags\/v//}"
          CHANGELOG=`cat ./$version.md`
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          release_tag: ${{ github.ref }}
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          body: "${{ env.CHANGELOG }}"
